touch "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.s1"
echo 1 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.s2"
echo 2 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.s3"
echo 3 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.s4"
echo 4 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.s5"
echo 5 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.s6"
echo 6 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.s7"
echo 7 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.s8"
echo 8 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.s9"
echo 9 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.s10"
echo 10 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.s11"
echo 11 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.s12"
echo 12 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d1"
echo 13 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d2"
echo 14 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d3"
echo 15 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d4"
echo 16 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d5"
echo 17 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d6"
echo 18 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d7"
echo 19 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d8"
echo 20 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d9"
echo 21 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d10"
echo 22 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d11"
echo 23 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d12"
echo 24 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d13"
echo 25 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d14"
echo 26 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d15"
echo 27 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d16"
echo 28 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d17"
echo 29 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d18"
echo 30 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d19"
echo 31 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw1.d20"
echo 32 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.s1"
echo 1 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.s2"
echo 2 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.s3"
echo 3 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.s4"
echo 4 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.s5"
echo 5 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.s6"
echo 6 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.s7"
echo 7 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.s8"
echo 8 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.s9"
echo 9 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.s10"
echo 10 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.s11"
echo 11 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.s12"
echo 12 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d1"
echo 13 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d2"
echo 14 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d3"
echo 15 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d4"
echo 16 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d5"
echo 17 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d6"
echo 18 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d7"
echo 19 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d8"
echo 20 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d9"
echo 21 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d10"
echo 22 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d11"
echo 23 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d12"
echo 24 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d13"
echo 25 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d14"
echo 26 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d15"
echo 27 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d16"
echo 28 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d17"
echo 29 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d18"
echo 30 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d19"
echo 31 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
"/Users/administrator/Desktop/homer2-scm-2018-12-16/PACKAGES/tMCimg/bin/Darwin//tMCimg"  "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw/fw2.d20"
echo 32 > "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_start"
touch "/Volumes/PegasusDDLab/Pipeline/06IND003G/digitization/fw//.fw_all_stop"
